// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using OrbitalGuard.Data;

#nullable disable

namespace OrbitalGuard.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260607175120_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OrbitalGuard.Models.AlertaDesastre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataHoraAlerta")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime?>("DataHoraResolucao")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("LeituraClimaticaId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("NivelAlerta")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("RegiaoMonitoradaId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<bool>("Resolvido")
                        .HasColumnType("NUMBER(1)");

                    b.Property<int>("TipoDesastre")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("LeituraClimaticaId");

                    b.HasIndex("RegiaoMonitoradaId");

                    b.ToTable("TB_ALERTAS", (string)null);
                });

            modelBuilder.Entity("OrbitalGuard.Models.LeituraClimatica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("IndiceRisco")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double>("PressaoHpa")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<int>("RegiaoMonitoradaId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("SateliteId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<double>("TemperaturaC")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<double>("UmidadePercent")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double>("VelocidadeVentoKmh")
                        .HasColumnType("BINARY_DOUBLE");

                    b.HasKey("Id");

                    b.HasIndex("RegiaoMonitoradaId");

                    b.HasIndex("SateliteId");

                    b.ToTable("TB_LEITURAS", (string)null);
                });

            modelBuilder.Entity("OrbitalGuard.Models.RegiaoMonitorada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("AreaKm2")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double>("Latitude")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double>("Longitude")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("TB_REGIOES", (string)null);
                });

            modelBuilder.Entity("OrbitalGuard.Models.Satelite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("AltitudeKm")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<bool>("Ativo")
                        .HasColumnType("NUMBER(1)");

                    b.Property<double>("CoberturaDegraus")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<DateTime>("DataLancamento")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Fabricante")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("TipoOrbita")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("TB_SATELITES", (string)null);
                });

            modelBuilder.Entity("OrbitalGuard.Models.AlertaDesastre", b =>
                {
                    b.HasOne("OrbitalGuard.Models.LeituraClimatica", "LeituraClimatica")
                        .WithMany("Alertas")
                        .HasForeignKey("LeituraClimaticaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OrbitalGuard.Models.RegiaoMonitorada", null)
                        .WithMany("Alertas")
                        .HasForeignKey("RegiaoMonitoradaId");

                    b.Navigation("LeituraClimatica");
                });

            modelBuilder.Entity("OrbitalGuard.Models.LeituraClimatica", b =>
                {
                    b.HasOne("OrbitalGuard.Models.RegiaoMonitorada", "RegiaoMonitorada")
                        .WithMany("Leituras")
                        .HasForeignKey("RegiaoMonitoradaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OrbitalGuard.Models.Satelite", "Satelite")
                        .WithMany("leituras")
                        .HasForeignKey("SateliteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RegiaoMonitorada");

                    b.Navigation("Satelite");
                });

            modelBuilder.Entity("OrbitalGuard.Models.LeituraClimatica", b =>
                {
                    b.Navigation("Alertas");
                });

            modelBuilder.Entity("OrbitalGuard.Models.RegiaoMonitorada", b =>
                {
                    b.Navigation("Alertas");

                    b.Navigation("Leituras");
                });

            modelBuilder.Entity("OrbitalGuard.Models.Satelite", b =>
                {
                    b.Navigation("leituras");
                });
#pragma warning restore 612, 618
        }
    }
}
